### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Deraen** [adzerk-oss/boot-cljs#69]
Okay, boot-cljs is finally updated. There is still however much to improve.

Some general ideas:
- Boot-cljs should do as little as possible and let the cljs compiler take care of everything

- [ ] No need to follow Clojurescript versioning
  - Current version should work with any cljs from version 3196+
  - The API should be quite stable nowadays
  - `cljs.compiler.api`
- [ ] Multiple build refactor, #55
  - Currently one cljs task will handle multiple .cljs.edn files
  - Each cljs.edn might have different compiler options or such
  - Each build would use the same output dir causing problems if there are conflicting options
  - Solution: If multiple builds are needed, multiple cljs task should be used. `(comp (cljs :id "browser") (cljs :id "node"))` and cljs.edn files should probably have `:id` property.
- [ ] Integrate cljs-repl
  - boot-cljs-repl wont work with latest version
- [ ] Make :main option required? #57
  - Default main currently requires all cljs namespaces found and I don't think this is a wise decision
  - Cljs compiler requires `:main` option if shim is to be used

**Comment by pkobrien** [comment]
I think I've got boot-cljs-repl working now. Please test it and let me know how it works for you.

**Comment by Deraen** [comment]
Most of the changes either implemented, on hold or tested and decided not a good idea.

- We'll use Cljs versioning still as Cljs API is still a bit in flux and we anyhow require the latest version
- Multiple builds refactor done, but will be partly reverted so that it's still possible to compile multiple builds using one `cljs` task
- Cljs-repl not integreated yet. Still on rader, might be on the release after current changes have been released.
